/* glucose_model.h - generated by the training notebook. Do not edit by hand.
 *
 * LightGBM, 400 trees, 24400 nodes, 22 features.
 * Target: deviation from the subject's own calibration baseline, in mg/dL.
 *     glucose_mg_dl = baseline + gm_predict_delta(z)
 * where z[] is the feature vector z-scored against that subject's calibration window.
 *
 * All arrays are const -> they live in flash (.rodata). Nothing is copied to RAM.
 */
#ifndef GLUCOSE_MODEL_H
#define GLUCOSE_MODEL_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define GM_N_FEATURES 22
#define GM_N_TREES    400
#define GM_N_NODES    24400
#define GM_BIAS       0.0f

/* clinical constants, mirrored from the notebook config */
#define GM_GLU_MIN    41.0f
#define GM_GLU_MAX    399.0f
#define GM_RULE_LO    80.0000f   /* below this -> low   */
#define GM_RULE_HI    170.0000f   /* above this -> high  */

typedef enum { GM_LOW = 0, GM_NORMAL = 1, GM_HIGH = 2 } gm_state_t;

/* feat >= 0 : split on that feature, go left when x <= thr
 * feat <  0 : leaf, thr holds the leaf value
 * left/right are indices RELATIVE to the start of this tree                     */
typedef struct {
    int8_t  feat;
    uint8_t dleft;      /* NaN goes left when 1 */
    int16_t left;
    int16_t right;
    float   thr;
} gm_node_t;

extern const gm_node_t gm_nodes[GM_N_NODES];
extern const uint32_t  gm_tree_start[GM_N_TREES];
extern const char *const gm_feature_names[GM_N_FEATURES];

/* ---- inference ---- */
float      gm_predict_delta(const float z[GM_N_FEATURES]);
float      gm_predict_glucose(const float z[GM_N_FEATURES], float baseline);
gm_state_t gm_classify(float glucose_mg_dl);
const char *gm_state_name(gm_state_t s);

/* ---- per-subject calibration ----
 * Feed every calibration window through gm_calib_add(), then gm_calib_finish().
 * After that, gm_apply_calib() turns a raw feature vector into the z[] the model wants. */
typedef struct {
    float    mean[GM_N_FEATURES];
    float    m2[GM_N_FEATURES];     /* Welford running sum of squares */
    float    sd[GM_N_FEATURES];
    float    baseline;              /* mean reference glucose over the calibration window */
    float    glu_sum;
    uint16_t n;
    uint16_t n_glu;
    uint8_t  ready;
} gm_calib_t;

void gm_calib_init(gm_calib_t *c);
void gm_calib_add(gm_calib_t *c, const float raw[GM_N_FEATURES]);
void gm_calib_add_reference(gm_calib_t *c, float glucose_mg_dl);
int  gm_calib_finish(gm_calib_t *c);                 /* 1 on success, 0 if too few windows */
void gm_apply_calib(const gm_calib_t *c, const float raw[GM_N_FEATURES], float z[GM_N_FEATURES]);

#ifdef __cplusplus
}
#endif
#endif /* GLUCOSE_MODEL_H */
